-- Extend order lifecycle for payment-gated checkout and fulfillment.
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_PENDING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_FAILED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';

ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "paymentProvider" TEXT,
  ADD COLUMN IF NOT EXISTS "paymentSessionId" TEXT,
  ADD COLUMN IF NOT EXISTS "paymentIntentId" TEXT,
  ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "customerEmail" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingName" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingLine1" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingLine2" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingCity" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingState" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingPostalCode" TEXT,
  ADD COLUMN IF NOT EXISTS "shippingCountry" TEXT,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "Order_paymentSessionId_key" ON "Order"("paymentSessionId");

