import { STORE_NAME } from "./brand";

export const copy = {
  brand: {
    name: STORE_NAME,
  },
  nav: {
    home: "Home",
    products: "Products",
    orders: "Orders",
    cart: "Cart",
    admin: "Admin",
    seller: "Seller hub",
    login: "Sign in",
    logout: "Sign out",
    profile: "Profile",
  },
  home: {
    hero: {
      slides: [
        {
          id: "seasonal",
          eyebrow: "Seasonal sale",
          title: "Save up to 40% on selected items",
          description:
            "Limited-time offers across fashion, home, and everyday essentials.",
          cta: "Shop sale",
          href: "/#shop",
          image:
            "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80",
          accent: "from-orange-500/90 via-rose-500/80 to-fuchsia-600/85",
        },
        {
          id: "electronics",
          eyebrow: "New arrivals",
          title: "Electronics for work and home",
          description:
            "Laptops, audio, accessories, and more from trusted brands.",
          cta: "Shop electronics",
          href: "/#shop",
          image:
            "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1600&q=80",
          accent: "from-slate-900/90 via-indigo-900/80 to-violet-700/85",
        },
        {
          id: "home",
          eyebrow: "Home & living",
          title: "Furnish and refresh your space",
          description:
            "Furniture, kitchenware, and decor for every room.",
          cta: "Shop home",
          href: "/#shop",
          image:
            "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=80",
          accent: "from-emerald-800/90 via-teal-800/80 to-cyan-700/85",
        },
      ],
    },
    categories: {
      eyebrow: "Categories",
      title: "Shop by category",
      clear: "Clear filter",
    },
    catalog: {
      eyebrow: "Products",
      title: "All products",
      description: "Search and filter to find what you need.",
      compactTitle: "Product catalog",
    },
  },
  catalog: {
    searchPlaceholder: "Search by name or keyword",
    filters: "Filters",
    clear: "Clear filters",
    inStockOnly: "In stock only",
    noResultsTitle: "No products found",
    noResultsDescription: "Try different keywords or adjust your filters.",
    loading: "Loading products…",
    results: (count: number) =>
      count === 1 ? "1 product" : `${count} products`,
  },
  auth: {
    signIn: {
      title: "Sign in",
      description: "Access your cart, orders, and account settings.",
      submit: "Sign in",
      noAccount: "Don't have an account?",
      registerLink: "Create account",
    },
    register: {
      title: "Create account",
      description: "Join as a buyer to shop, or as a seller to list products on the marketplace.",
      submit: "Create account",
      buyerLabel: "Buyer — shop and checkout",
      sellerLabel: "Seller — list and fulfill products",
    },
    verifyEmail: {
      title: "Verifying email",
      verifying: "Confirming your email address…",
      missingToken: "This verification link is invalid. Request a new one below.",
      successTitle: "Email verified",
      successDescription: "Your account is ready. Sign in to continue.",
      error: "Verification failed. The link may have expired.",
      backToSignIn: "Back to sign in",
      resendCta: "Resend verification email",
      signInCta: "Sign in",
    },
    verifyPending: {
      title: "Verify your email",
      description:
        "We sent a verification link to your inbox. Confirm your email before using cart, checkout, seller, or admin features.",
      resend: "Resend verification email",
      sending: "Sending…",
      resendSuccess: "Verification email sent. Check your inbox.",
      backToSignIn: "Back to sign in",
    },
  },
  profile: {
    eyebrow: "Account",
    title: "Profile",
    description: "Update your name and profile photo.",
    changePhoto: "Change photo",
    photoHint: "JPG, PNG, or WebP up to 5 MB. Saved as optimized WebP.",
    displayName: "Display name",
    email: "Email",
    save: "Save changes",
    saving: "Saving…",
    noChanges: "No changes to save",
    success: "Profile updated",
    error: "Could not update profile",
  },
  cart: {
    title: "Shopping cart",
    emptyTitle: "Your cart is empty",
    emptyDescription: "Browse products and add items to checkout.",
    continueShopping: "Continue shopping",
    summary: "Order summary",
    checkout: "Proceed to checkout",
    loading: "Loading cart…",
    signInToCheckout: "Sign in to checkout",
  },
  checkoutPage: {
    title: "Checkout",
    description: "Enter your delivery address, then continue to payment.",
    deliveryTitle: "Delivery address",
    orderSummary: "Order summary",
    placeOrder: "Continue to payment",
    processing: "Preparing checkout…",
    backToCart: "Back to cart",
    emptyCart: "Your cart is empty. Add items before checkout.",
  },
  orders: {
    title: "Orders",
    emptyTitle: "No orders yet",
    emptyDescription: "Your order history will appear here after checkout.",
    continueShopping: "Browse products",
    loading: "Loading orders…",
  },
  product: {
    notFoundTitle: "Product not found",
    notFoundDescription: "This item may have been removed or is unavailable.",
    backToShop: "Back to shop",
    secureCheckout: "Secure checkout",
    secureCheckoutDescription: "Payments are processed securely at checkout.",
    liveInventory: "Stock availability",
    liveInventoryDescription: "Quantity is verified before you pay.",
    orderTracking: "Order updates",
    orderTrackingDescription: "Track status from payment through delivery.",
  },
  checkout: {
    successEyebrow: "Order confirmed",
    successTitle: "Thank you for your order",
    cancelEyebrow: "Checkout cancelled",
    cancelTitle: "Your cart is still saved",
  },
} as const;
